# Authors:     BP
# Maintainers: BP
# Copyright:   2022, HRDAG, GPL v2 or later
# =========================================
# sample_project/import/Makefile

.PHONY: all export preproc

all: preproc export

export: preproc
	cd $@ && make

preproc: 
	cd $@ && make

# done.