# Authors:     BP
# Maintainers: BP
# Copyright:   2022, HRDAG, GPL v2 or later
# =========================================
# sample_project/compas-scores/Makefile

.PHONY: all import

all: import

import:
	cd $@ && make

# done.